version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgres:alpine3.17
    hostname: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}
